# Numpy

### Numply Array

In [1]:
# 리스트와 넘파이 어레이 속도 비교
import numpy as np
np_arr = np.arange(100000)
nu_list = [i for i in range(100000)]

In [2]:
%%time 
for i in range(100):
    sum(nu_list)

Wall time: 166 ms


In [3]:
%%time
for i in range(100):
    sum = 0
    np.sum(np_arr)

Wall time: 5 ms


### 1차원 배열 만들기

In [4]:
ar = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
type(ar)

numpy.ndarray

In [6]:
ar.shape

(10,)

In [10]:
al = [2 * i for i in range(1,11)]
al

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [9]:
2 * ar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
2 * al

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [12]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [13]:
2 * a + b

array([12, 24, 36])

In [14]:
a == 2

array([False,  True, False])

In [15]:
b > 15

array([False,  True,  True])

In [16]:
(a == 2) & (b > 10)

array([False,  True, False])

### 2차원 배열

In [17]:
c = np.array([[0, 1, 2],[3, 4, 5]])
c

array([[0, 1, 2],
       [3, 4, 5]])

In [18]:
c.shape

(2, 3)

In [19]:
len(c),len(c[0])

(2, 3)

In [22]:
d = np.array([[10, 20, 30, 40],[50, 60, 70, 80]])
d

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

### 3차원 배열

In [23]:
d = np.array([[[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]],[[11, 12, 13, 14],[15, 16, 17, 18],[19, 20, 21, 22]]])
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [27]:
d.shape,d.ndim

((2, 3, 4), 3)

### 배열의 인덱싱

In [28]:
a = np.array([0, 1, 2, 3, 4])

In [30]:
a[2],a[-1]

(2, 4)

In [32]:
a = np.array([[0, 1, 2],[3, 4, 5]])
a[1, 0]

3

### 배열 슬라이싱

In [33]:
a = np.array([[0, 1, 2, 3],[4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [34]:
a[:, 1:3]

array([[1, 2],
       [5, 6]])

In [36]:
a = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9],[10, 11, 12, 13, 14]])
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [38]:
a[1, 2]

7

In [39]:
a[2, -1]

14

In [48]:
print(a[1,1:3])
print(a[1:,2])
print(a[0:2,3:5])

[6 7]
[ 7 12]
[[3 4]
 [8 9]]


### 배열 인덱싱

In [50]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False,True, False,True, False,True, False ])
a[idx]

array([0, 2, 4, 6, 8])

In [51]:
a % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [53]:
a[a % 2 == 0]

array([0, 2, 4, 6, 8])

In [54]:
a = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = np.array([0, 2, 4, 6, 8])
a[idx]

array([11, 33, 55, 77, 99])

In [55]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [56]:
a[:,[True, False, True, False]]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [57]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [58]:
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [59]:
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [69]:
x[(x % 4 == 1) * (x % 3 == 0 )]

array([9])