# 배열 생성

In [1]:
import numpy as np

### 넘파이의 자료형

In [2]:
x = np.array([1, 2, 3])
x.dtype

dtype('int32')

In [3]:
x = np.array([1.0, 2.0, 3.0])
x.dtype

dtype('float64')

In [5]:
x = np.array([1, 2, 3], dtype='f')
x.dtype

dtype('float32')

### Inf와 Nan

In [4]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

array([  0.,  inf, -inf,  nan])

In [6]:
np.log(0)

-inf

In [7]:
np.exp(-np.inf)

0.0

In [8]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [9]:
a.dtype

dtype('float64')

In [10]:
b = np.zeros((2, 3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
c = np.zeros((2, 5), dtype="i")
c

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [12]:
c.dtype

dtype('int32')

In [13]:
np.ones(4)

array([1., 1., 1., 1.])

In [14]:
np.ones_like(b)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
g = np.empty((4, 3))
g

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(3, 21, 2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [18]:
np.linspace(0, 100 ,5)

array([  0.,  25.,  50.,  75., 100.])

In [19]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

In [20]:
np.log(np.logspace(0.1, 1, 10))

array([0.23025851, 0.46051702, 0.69077553, 0.92103404, 1.15129255,
       1.38155106, 1.61180957, 1.84206807, 2.07232658, 2.30258509])

### 전치 연산 (Transpose)

In [22]:
A = np.array([[1, 2, 3,],[4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [24]:
A.T @ A

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [25]:
A @ A.T

array([[14, 32],
       [32, 77]])

### 배열의 크기 변형

In [26]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [27]:
b = a.reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
a.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
a.reshape(-1, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [30]:
a.reshape(3, 2, -1)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [31]:
a.reshape(2, -1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [32]:
print(b)
print(b.flatten())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [33]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [34]:
x.reshape(1, -1)

array([[0, 1, 2, 3, 4]])

In [35]:
x.reshape(5, 1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [36]:
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

### 배열 연결

In [37]:
a1 = np.ones([2, 3])
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [38]:
a2 = np.zeros((2, 3))
a2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [39]:
np.hstack([a1, a2])

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [40]:
b1 = np.ones([2, 3])
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [41]:
b2 = np.zeros((3, 3))
b2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [42]:
np.vstack([b1, b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
b = np.ones((3,2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [45]:
c = np.hstack([a, b])
c

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [46]:
d = np.arange(10,151,10)
d

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150])

In [47]:
e = d.reshape(3, -1)
e

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150]])

In [48]:
f = np.vstack([c, e])
f

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [49]:
g = np.vstack([f, f])
g

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

### 2차원 그리드 포인트 생성

In [50]:
x = np.arange(3)
x

array([0, 1, 2])

In [51]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [54]:
X, Y = np.meshgrid(x, y)

In [55]:
X

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [56]:
Y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [57]:
[list(zip(x, y)) for x, y in zip(X, Y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]