# 난수 발생과 카운팅

In [1]:
import numpy as np

### 시드 설정하기

In [2]:
np.random.rand(5)

array([0.79582373, 0.2906464 , 0.06716927, 0.85750762, 0.87932449])

In [3]:
np.random.rand(5)

array([0.48244366, 0.84212293, 0.504936  , 0.14382919, 0.3549622 ])

In [5]:
np.random.seed(2020)
np.random.rand(5)

array([0.98627683, 0.87339195, 0.50974552, 0.27183571, 0.33691873])

In [6]:
np.random.seed(2020)
np.random.rand(5)

array([0.98627683, 0.87339195, 0.50974552, 0.27183571, 0.33691873])

### 데이터의 순서 바꾸기

In [7]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.random.shuffle(x)
x

array([5, 7, 6, 4, 3, 1, 2, 8, 9, 0])

### 데이터 샘플링

In [11]:
np.random.choice(5, 5, replace = False)

array([0, 2, 3, 1, 4])

In [12]:
np.random.choice(5, 5, replace = True)

array([2, 1, 2, 4, 4])

In [13]:
np.random.choice(5, 3, replace = False)


array([4, 1, 0])

In [14]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])


array([2, 0, 3, 3, 3, 3, 3, 3, 2, 3])

### 난수 생성

In [15]:
np.random.randn(10)

array([-0.97232061, -0.1383119 , -1.98764929,  0.42246929, -0.25438059,
        0.64496689, -0.12015076, -0.48352493,  0.53825049,  1.23793055])

In [16]:
np.random.randint(10, size = 10)

array([9, 5, 1, 9, 0, 1, 7, 5, 0, 7])

In [22]:
today = 10000
tommorow = today * (1 + np.random.randn(1)/100.0)
tommorow

array([9857.66056912])

In [26]:
prices = []
price = 10000
for i in range(250):
    tmp = price * (1 + np.random.randn(1)/100.0)
    price = tmp[0]
    prices.append(price)
prices

[9878.599313218192,
 9833.365176832262,
 9968.284501781915,
 10003.851836700833,
 10064.694615500353,
 10060.54538478076,
 10133.169811077012,
 10070.647664260086,
 10116.674181312601,
 10069.312455009025,
 10060.363048129113,
 10281.958870487662,
 10387.714181193958,
 10434.158167742055,
 10375.5929924711,
 10396.918555037752,
 10397.828684026186,
 10443.62898879522,
 10505.302062852601,
 10564.011099434429,
 10454.612901584152,
 10392.89636350189,
 10052.840229006817,
 9967.90143483324,
 10216.563781437242,
 10053.601780541789,
 10014.043734125256,
 10151.090128354479,
 10353.469625524529,
 10353.653045310779,
 10256.522828231708,
 10138.317043687754,
 10053.152355250224,
 10111.046352882604,
 10257.596053470843,
 10375.206453790644,
 10414.424300220162,
 10459.501768358123,
 10453.116217921808,
 10459.97419277387,
 10522.710837742137,
 10574.31354761148,
 10640.947036645708,
 10690.192037576122,
 10620.028290567927,
 10675.783539606526,
 10524.051113842426,
 10576.352084348757,
 105

### 정수 데이터 카운팅

In [27]:
np.unique([11, 11, 2, 2, 34, 34])

array([ 2, 11, 34])

In [28]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)

In [29]:
print(index,count)

['a' 'b' 'c'] [2 2 1]


In [30]:
np.bincount([1, 1, 2, 2, 2, 3], minlength=6)

array([0, 2, 3, 1, 0, 0], dtype=int64)