# 벡터와 벡터의 곱셉

In [1]:
import numpy as np

In [4]:
x = np.arange(1,4).reshape(3, 1)
y = np.arange(4, 7).reshape(3, 1)
print(x)
print(y)

[[1]
 [2]
 [3]]
[[4]
 [5]
 [6]]


In [5]:
x.shape,y.shape

((3, 1), (3, 1))

In [6]:
x.T.shape

(1, 3)

In [7]:
z = x.T @ y
z

array([[32]])

In [8]:
z.shape

(1, 1)

In [9]:
z[0, 0]

32

In [10]:
np.dot(x.T, y)

array([[32]])

In [13]:
x = np.arange(1,7).reshape(2, 3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
x @ x.T

array([[14, 32],
       [32, 77]])

In [15]:
p = np.array([1000000, 800000, 500000])
n = np.array([3, 4, 5])
p , n

(array([1000000,  800000,  500000]), array([3, 4, 5]))

In [17]:
money = p @ n.T
print(money)

8700000


In [18]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 2], [3, 4], [5, 6]])

In [19]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
A @ B

array([[22, 28],
       [49, 64]])

In [22]:
B @ A

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [25]:
A = np.array([1, 2, 3])
B = np.array([[4, 7],[5, 8],[6, 9]])

In [26]:
A

array([1, 2, 3])

In [27]:
B

array([[4, 7],
       [5, 8],
       [6, 9]])

In [28]:
A @ B

array([32, 50])

In [29]:
B @ A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [30]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [31]:
A @ B

array([[19, 22],
       [43, 50]])

In [32]:
B @ A

array([[23, 34],
       [31, 46]])

In [33]:
A = np.array([[1, 2],[3, 4],[5, 6]])

In [34]:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [36]:
A.T

array([[1, 3, 5],
       [2, 4, 6]])

In [37]:
A @ A.T

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

In [38]:
A.T @ A

array([[35, 44],
       [44, 56]])