# 벡터와 벡터의 곱셉

In [1]:
import numpy as np

In [4]:
x = np.arange(1,4).reshape(3, 1)
y = np.arange(4, 7).reshape(3, 1)
print(x)
print(y)

[[1]
 [2]
 [3]]
[[4]
 [5]
 [6]]


In [5]:
x.shape,y.shape

((3, 1), (3, 1))

In [6]:
x.T.shape

(1, 3)

In [7]:
z = x.T @ y
z

array([[32]])

In [8]:
z.shape

(1, 1)

In [9]:
z[0, 0]

32

In [10]:
np.dot(x.T, y)

array([[32]])

In [13]:
x = np.arange(1,7).reshape(2, 3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
x @ x.T

array([[14, 32],
       [32, 77]])

In [ ]:
for i in range(len(x)):
    val = 0
    for k in range(len(x[0])):
        for n in range