In [1]:
import numpy as np

In [4]:
# 11 - 1
a = np.zeros(10)

In [5]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
# 11 - 2
b = np.eye(1,10,k=5)
b

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]])

In [10]:
# 11 - 3
c = np.arange(10,50)
c

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [14]:
# 11 - 4
np.random.shuffle(c)
c

array([42, 40, 32, 48, 31, 49, 34, 11, 30, 20, 39, 19, 46, 41, 36, 28, 29,
       47, 13, 25, 10, 27, 43, 38, 44, 37, 14, 21, 15, 45, 23, 12, 35, 26,
       18, 16, 22, 17, 33, 24])

In [36]:
# 11 - 5
d = np.arange(0,9).reshape((3,3))
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [37]:
# 11 - 6
e = np.array([1, 2, 0, 0, 4, 0])
e

array([1, 2, 0, 0, 4, 0])

In [38]:
e[e != 0]

array([1, 2, 4])

In [39]:
# 11 - 7
f = np.identity(n = 3,dtype = np.int8)
f

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [40]:
# 11 - 8
g = np.random.rand(9).round(2).reshape((3,3))
g

array([[0.49, 0.86, 0.79],
       [0.43, 0.24, 0.23],
       [0.46, 0.3 , 0.17]])

In [41]:
# 11 - 9
np.max(g),np.min(g)

(0.86, 0.17)

In [44]:
# 11 - 10
np.mean(g, axis = 0) # 열 평균

array([0.46      , 0.46666667, 0.39666667])

In [45]:
np.mean(g, axis = 1) # 행 평균

array([0.71333333, 0.3       , 0.31      ])